spring:
  application:
    name: hexagonal
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

thiiagoms:
  client:
    address:
        url: https://localhost:80828/addressses